### ISSUE TITLE
error: this is not a node_modules folder — improve installation instructions

### ISSUE THREAD

**Issue by Snaptags** [danmarshall/deckgl-typings#27]
I'm trying to use this module for my app. This is what I tried to integrate your typings:

```
npm install indefinitely-typed
git clone https://github.com/danmarshall/deckgl-typings .\src\typings\deckgl-typing
```

Then I added this to my package.json:
`    "postinstall": "indefinitely-typed --folder ./src/typings/deckgl-typings"`

Unfortunately _npm install_ fails, reporting:

```
indefinitely-typed installation ...
args: { _: [], folder: './src/typings/deckgl-typings' }
cwd: D:\dev\myapp\ui
looking for package.json at: D:\dev\myapp\ui\package.json
package name is : my-app
package is not scoped.
using node_modules at D:\dev\myapp
error: this is not a node_modules folder.
```

Shouldn't it be looking for the node_modules folder in the same directory where the package.json is located ("ui" in my case)?

Any idea?

**Comment by Snaptags** [comment]
Maybe a Windows-only issue concerning [indefinitely-typed](https://github.com/danmarshall/indefinitely-typed/issues/1)

**Comment by danmarshall** [comment]
Hi @Snaptags , thanks for the feedback. I will need to add this to the readme.
Please uninstall `indefinitely-typed`, it should not be used directly, it is "under the hood" of this project.
You should only need to `npm install @danmarshall/deckgl-typings'. Can you try that and let me know if your issue is solved.

Also, you can see an example project that consumes these typings: https://github.com/danmarshall/deckgl-typescript-example

**Comment by Snaptags** [comment]
Installing the typings like you suggest worked without any problems, thanks!
